version: '3'
services:
  app-main:
    build:
      context: .
      args:
        - BRANCH=main
    ports:
      - "3000:3000"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2

  app-testing:
    build:
      context: .
      args:
        - BRANCH=testing
    ports:
      - "3001:3000"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3

networks:
  mynetwork:
    external: true